### PR TITLE
Report tab: report marker, search field auto-fill from marker, divs to help fix map height issue

### PR DESCRIPTION
**Pull request by stewartreichling**
Notes:
- map height issue on report tab not yet resolved.
- need to find a way to update marker during drag (vs. only after drag)

### CODE REVIEW

**Comment by werdnanoslen** [comment]
Nice! It's close, but there are a couple of issues
1. Dragend isn't the right handler, because that's only when the finger stops dragging; however, the map sort of coasts along with the inertia the dragging gave it. So find the right handler for where the map _movement_ stops rather than the finger dragging.
2. The marker should stay put in the middle of the map while dragging so that the user can precisely place the marker (drag around on the map on Uber to see what I'm talking about). An open question though: if places are far apart and the user drops a pin away from them, should it geocode an address or use the lat/lon?

Also, I use 4 space indentations in all my projects, so let's use that. I'm adding an .editorconfig file now...

**Comment by stewartreichling** [comment]
Made some progress!
1. using idle event instead of dragend
2. replaced the marker object with an image that's injected into the center of the map view. Way smoother scrolling and it should always be right in the center
   -- can you clarify what you mean re: geocode the address vs lat/lon?

I also figured out how to make the map size correctly rather than overflow the boundaries.

**Comment by stewartreichling** [comment]
Hmm, there might be a bug. Address in the form isn't updating after I manually search for an address and then move the pin.

**Comment by werdnanoslen** [comment]
Yep, that and the address isn't being set when the map is allowed to coast (as in you flick instead of drag).

**Comment by stewartreichling** [comment]
It should be. The event is 'idle' which should fire once panning is over.
As far as I can tell, that includes the coast but I'll take another look.

**Comment by werdnanoslen** [comment]
Hey, I merged your changes in with some other edits from 12c6b5390c20b341123a29f19362175535cf3ac2 to 3c21ea2f23dcd10e3df3f712d6d4cb75a2f02d4c

**Pull request merged**
